name: Ansible CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ansible-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          python3 -m pip install --upgrade pip
          pip install ansible ansible-lint

      - name: Syntax Check
        run: |
          ansible-playbook playbook.yml --syntax-check

      - name: Run ansible-lint
        run: |
          ansible-lint
